import { jsPDF } from "jspdf";

export type ClinicalPdfRiskLevel =
  | "low"
  | "moderate"
  | "high"
  | "very-high"
  | "neutral";

export type ClinicalPdfReportData = {
  calculatorName: string;
  calculatorFullName?: string;
  category?: string;
  score: string | number;
  scoreLabel?: string;
  riskLabel: string;
  riskLevel: ClinicalPdfRiskLevel;
  interpretation: string;
  components?: string[];
  warning?: string;
  reference?: string;
  disclaimer?: string;
};

type PdfColor = [number, number, number];

const PAGE_WIDTH = 210;
const PAGE_HEIGHT = 297;

const MARGIN_X = 18;
const TOP_MARGIN = 18;
const BOTTOM_MARGIN = 18;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN_X * 2;

const COLORS = {
  background: [4, 10, 25] as PdfColor,
  panel: [13, 22, 42] as PdfColor,
  panelSecondary: [17, 27, 49] as PdfColor,
  white: [244, 247, 252] as PdfColor,
  text: [190, 201, 220] as PdfColor,
  muted: [119, 137, 165] as PdfColor,
  cyan: [67, 214, 236] as PdfColor,
  emerald: [52, 211, 153] as PdfColor,
  amber: [251, 191, 36] as PdfColor,
  rose: [251, 113, 133] as PdfColor,
  violet: [196, 181, 253] as PdfColor,
  border: [40, 55, 82] as PdfColor,
};

function setFillColor(
  pdf: jsPDF,
  color: PdfColor,
) {
  pdf.setFillColor(color[0], color[1], color[2]);
}

function setDrawColor(
  pdf: jsPDF,
  color: PdfColor,
) {
  pdf.setDrawColor(color[0], color[1], color[2]);
}

function setTextColor(
  pdf: jsPDF,
  color: PdfColor,
) {
  pdf.setTextColor(color[0], color[1], color[2]);
}

function getRiskColor(
  riskLevel: ClinicalPdfRiskLevel,
): PdfColor {
  switch (riskLevel) {
    case "low":
      return COLORS.emerald;

    case "moderate":
      return COLORS.amber;

    case "high":
    case "very-high":
      return COLORS.rose;

    default:
      return COLORS.cyan;
  }
}

function sanitizeFilename(value: string) {
  return value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function formatGeneratedDate() {
  return new Intl.DateTimeFormat("en-GB", {
    dateStyle: "long",
    timeStyle: "short",
  }).format(new Date());
}

function drawPageBackground(pdf: jsPDF) {
  setFillColor(pdf, COLORS.background);

  pdf.rect(
    0,
    0,
    PAGE_WIDTH,
    PAGE_HEIGHT,
    "F",
  );

  setDrawColor(pdf, [12, 33, 55]);

  pdf.setLineWidth(0.15);

  for (let x = 0; x <= PAGE_WIDTH; x += 12) {
    pdf.line(x, 0, x, PAGE_HEIGHT);
  }

  for (let y = 0; y <= PAGE_HEIGHT; y += 12) {
    pdf.line(0, y, PAGE_WIDTH, y);
  }

  setFillColor(pdf, [7, 29, 48]);

  pdf.circle(
    18,
    24,
    36,
    "F",
  );

  setFillColor(pdf, [20, 15, 53]);

  pdf.circle(
    PAGE_WIDTH - 8,
    PAGE_HEIGHT - 10,
    52,
    "F",
  );
}

function drawBrandHeader(
  pdf: jsPDF,
  calculatorName: string,
) {
  setFillColor(pdf, [5, 28, 47]);

  pdf.roundedRect(
    MARGIN_X,
    TOP_MARGIN,
    14,
    14,
    4,
    4,
    "F",
  );

  setDrawColor(pdf, COLORS.cyan);
  pdf.setLineWidth(0.4);

  pdf.roundedRect(
    MARGIN_X,
    TOP_MARGIN,
    14,
    14,
    4,
    4,
    "S",
  );

  setTextColor(pdf, COLORS.cyan);
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(9);
  pdf.text(
    "EP",
    MARGIN_X + 7,
    TOP_MARGIN + 9,
    {
      align: "center",
    },
  );

  setTextColor(pdf, COLORS.white);
  pdf.setFontSize(14);
  pdf.text(
    "EP-SCORE AI",
    MARGIN_X + 19,
    TOP_MARGIN + 5.8,
  );

  setTextColor(pdf, COLORS.muted);
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(8.5);
  pdf.text(
    "Clinical Risk Assessment Report",
    MARGIN_X + 19,
    TOP_MARGIN + 11,
  );

  setTextColor(pdf, COLORS.muted);
  pdf.setFontSize(8);
  pdf.text(
    calculatorName,
    PAGE_WIDTH - MARGIN_X,
    TOP_MARGIN + 8,
    {
      align: "right",
    },
  );
}

function drawFooter(
  pdf: jsPDF,
  pageNumber: number,
) {
  const footerY = PAGE_HEIGHT - 11;

  setDrawColor(pdf, COLORS.border);
  pdf.setLineWidth(0.3);

  pdf.line(
    MARGIN_X,
    footerY - 4,
    PAGE_WIDTH - MARGIN_X,
    footerY - 4,
  );

  setTextColor(pdf, COLORS.muted);
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(7.5);

  pdf.text(
    "Generated by EP-SCORE AI",
    MARGIN_X,
    footerY,
  );

  pdf.text(
    `Page ${pageNumber}`,
    PAGE_WIDTH - MARGIN_X,
    footerY,
    {
      align: "right",
    },
  );
}

function drawSectionLabel(
  pdf: jsPDF,
  label: string,
  x: number,
  y: number,
  color: PdfColor = COLORS.cyan,
) {
  setTextColor(pdf, color);
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(8);

  pdf.text(
    label.toUpperCase(),
    x,
    y,
  );
}

function drawWrappedText(
  pdf: jsPDF,
  text: string,
  x: number,
  y: number,
  maxWidth: number,
  options?: {
    fontSize?: number;
    lineHeight?: number;
    color?: PdfColor;
    fontStyle?: "normal" | "bold";
  },
) {
  const fontSize = options?.fontSize ?? 9.5;
  const lineHeight = options?.lineHeight ?? 5;
  const color = options?.color ?? COLORS.text;
  const fontStyle = options?.fontStyle ?? "normal";

  pdf.setFont("helvetica", fontStyle);
  pdf.setFontSize(fontSize);
  setTextColor(pdf, color);

  const lines = pdf.splitTextToSize(
    text,
    maxWidth,
  ) as string[];

  lines.forEach((line, index) => {
    pdf.text(
      line,
      x,
      y + index * lineHeight,
    );
  });

  return y + lines.length * lineHeight;
}

function addPage(
  pdf: jsPDF,
  calculatorName: string,
  pageNumber: number,
) {
  pdf.addPage();

  drawPageBackground(pdf);
  drawBrandHeader(pdf, calculatorName);
  drawFooter(pdf, pageNumber);

  return TOP_MARGIN + 26;
}

export function generateClinicalPdf(
  data: ClinicalPdfReportData,
) {
  const pdf = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
    compress: true,
  });

  drawPageBackground(pdf);
  drawBrandHeader(pdf, data.calculatorName);
  drawFooter(pdf, 1);

  let pageNumber = 1;
  let cursorY = TOP_MARGIN + 28;

  const ensureSpace = (
    requiredHeight: number,
  ) => {
    const maximumY =
      PAGE_HEIGHT - BOTTOM_MARGIN - 12;

    if (cursorY + requiredHeight <= maximumY) {
      return;
    }

    pageNumber += 1;

    cursorY = addPage(
      pdf,
      data.calculatorName,
      pageNumber,
    );
  };

  drawSectionLabel(
    pdf,
    data.category ?? "Clinical calculator",
    MARGIN_X,
    cursorY,
  );

  cursorY += 9;

  setTextColor(pdf, COLORS.white);
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(25);

  pdf.text(
    data.calculatorName,
    MARGIN_X,
    cursorY,
  );

  cursorY += 9;

  if (data.calculatorFullName) {
    cursorY = drawWrappedText(
      pdf,
      data.calculatorFullName,
      MARGIN_X,
      cursorY,
      CONTENT_WIDTH,
      {
        fontSize: 12,
        lineHeight: 5.5,
        color: COLORS.text,
        fontStyle: "bold",
      },
    );

    cursorY += 2;
  }

  cursorY = drawWrappedText(
    pdf,
    `Generated ${formatGeneratedDate()}`,
    MARGIN_X,
    cursorY,
    CONTENT_WIDTH,
    {
      fontSize: 8,
      lineHeight: 4,
      color: COLORS.muted,
    },
  );

  cursorY += 7;

  ensureSpace(55);

  const riskColor = getRiskColor(
    data.riskLevel,
  );

  setFillColor(pdf, COLORS.panel);
  setDrawColor(pdf, riskColor);

  pdf.setLineWidth(0.45);

  pdf.roundedRect(
    MARGIN_X,
    cursorY,
    CONTENT_WIDTH,
    50,
    6,
    6,
    "FD",
  );

  drawSectionLabel(
    pdf,
    "Calculated result",
    MARGIN_X + 8,
    cursorY + 9,
    riskColor,
  );

  setTextColor(pdf, COLORS.white);
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(30);

  pdf.text(
    String(data.score),
    MARGIN_X + 8,
    cursorY + 26,
  );

  if (data.scoreLabel) {
    setTextColor(pdf, COLORS.muted);
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(8);

    pdf.text(
      data.scoreLabel,
      MARGIN_X + 8,
      cursorY + 34,
    );
  }

  setTextColor(pdf, riskColor);
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(14);

  const riskLabelLines =
    pdf.splitTextToSize(
      data.riskLabel,
      87,
    ) as string[];

  pdf.text(
    riskLabelLines,
    MARGIN_X + 78,
    cursorY + 16,
  );

  drawWrappedText(
    pdf,
    data.interpretation,
    MARGIN_X + 78,
    cursorY + 27,
    87,
    {
      fontSize: 8.5,
      lineHeight: 4.4,
      color: COLORS.text,
    },
  );

  cursorY += 59;

  if (
    data.components &&
    data.components.length > 0
  ) {
    const estimatedHeight =
      20 + data.components.length * 10;

    ensureSpace(estimatedHeight);

    drawSectionLabel(
      pdf,
      "Score components",
      MARGIN_X,
      cursorY,
    );

    cursorY += 6;

    data.components.forEach((component) => {
      ensureSpace(10);

      setFillColor(
        pdf,
        COLORS.panelSecondary,
      );

      setDrawColor(pdf, COLORS.border);

      pdf.setLineWidth(0.25);

      pdf.roundedRect(
        MARGIN_X,
        cursorY,
        CONTENT_WIDTH,
        8,
        2,
        2,
        "FD",
      );

      setFillColor(pdf, COLORS.cyan);

      pdf.circle(
        MARGIN_X + 5,
        cursorY + 4,
        0.9,
        "F",
      );

      setTextColor(pdf, COLORS.text);
      pdf.setFont("helvetica", "normal");
      pdf.setFontSize(8.5);

      pdf.text(
        component,
        MARGIN_X + 9,
        cursorY + 5.2,
      );

      cursorY += 10;
    });

    cursorY += 3;
  }

  if (data.warning) {
    ensureSpace(35);

    setFillColor(pdf, [37, 30, 11]);
    setDrawColor(pdf, COLORS.amber);

    pdf.setLineWidth(0.35);

    pdf.roundedRect(
      MARGIN_X,
      cursorY,
      CONTENT_WIDTH,
      30,
      5,
      5,
      "FD",
    );

    drawSectionLabel(
      pdf,
      "Important clinical note",
      MARGIN_X + 7,
      cursorY + 8,
      COLORS.amber,
    );

    drawWrappedText(
      pdf,
      data.warning,
      MARGIN_X + 7,
      cursorY + 15,
      CONTENT_WIDTH - 14,
      {
        fontSize: 8.5,
        lineHeight: 4.5,
        color: COLORS.text,
      },
    );

    cursorY += 37;
  }

  ensureSpace(42);

  drawSectionLabel(
    pdf,
    "Clinical interpretation",
    MARGIN_X,
    cursorY,
  );

  cursorY += 7;

  setFillColor(pdf, COLORS.panel);
  setDrawColor(pdf, COLORS.border);

  pdf.roundedRect(
    MARGIN_X,
    cursorY,
    CONTENT_WIDTH,
    31,
    5,
    5,
    "FD",
  );

  drawWrappedText(
    pdf,
    data.interpretation,
    MARGIN_X + 7,
    cursorY + 9,
    CONTENT_WIDTH - 14,
    {
      fontSize: 9,
      lineHeight: 4.8,
      color: COLORS.text,
    },
  );

  cursorY += 39;

  if (data.reference) {
    ensureSpace(40);

    drawSectionLabel(
      pdf,
      "Scientific reference",
      MARGIN_X,
      cursorY,
      COLORS.violet,
    );

    cursorY += 7;

    setFillColor(pdf, COLORS.panel);
    setDrawColor(pdf, COLORS.border);

    pdf.roundedRect(
      MARGIN_X,
      cursorY,
      CONTENT_WIDTH,
      30,
      5,
      5,
      "FD",
    );

    drawWrappedText(
      pdf,
      data.reference,
      MARGIN_X + 7,
      cursorY + 9,
      CONTENT_WIDTH - 14,
      {
        fontSize: 8.5,
        lineHeight: 4.6,
        color: COLORS.text,
      },
    );

    cursorY += 37;
  }

  const disclaimer =
    data.disclaimer ??
    "This report is intended for clinical decision support and educational use. It does not replace professional medical judgment, complete patient assessment or specialist consultation.";

  ensureSpace(35);

  setDrawColor(pdf, COLORS.border);
  pdf.setLineWidth(0.3);

  pdf.line(
    MARGIN_X,
    cursorY,
    PAGE_WIDTH - MARGIN_X,
    cursorY,
  );

  cursorY += 7;

  drawSectionLabel(
    pdf,
    "Disclaimer",
    MARGIN_X,
    cursorY,
    COLORS.muted,
  );

  cursorY += 6;

  drawWrappedText(
    pdf,
    disclaimer,
    MARGIN_X,
    cursorY,
    CONTENT_WIDTH,
    {
      fontSize: 7.8,
      lineHeight: 4.2,
      color: COLORS.muted,
    },
  );

  const filenameBase =
    sanitizeFilename(data.calculatorName) ||
    "clinical-report";

  const datePart = new Date()
    .toISOString()
    .slice(0, 10);

  pdf.save(
    `${filenameBase}-report-${datePart}.pdf`,
  );
}